apiVersion: 1

datasources:
  - name: ${DATASOURCE_NAME}
    uid: ${DATASOURCE_UID}
    type: mysql
    access: proxy
    url: ${DORIS_HOST}:${DORIS_PORT}
    database: ${DORIS_DATABASE}
    user: ${DORIS_USER}
    secureJsonData:
      password: ${DORIS_PASSWORD}
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      timezone: ""
    isDefault: false
    editable: true
