USE ${DORIS_DATABASE};

CREATE TABLE bfe_ai_metrics_1m (
    ts_min             DATETIME        COMMENT '分钟时间桶',
    hostid             VARCHAR(256)    COMMENT '主机标识',
    ai_apikey_id       VARCHAR(128)    COMMENT 'API Key ID',
    ai_requested_model VARCHAR(128)    COMMENT '请求模型',
    ai_target_model    VARCHAR(128)    COMMENT '路由模型',
    ai_stream          TINYINT         COMMENT '流式标识',
    product            VARCHAR(64)     COMMENT '产品线',
    cluster            VARCHAR(64)     COMMENT '集群',
    sub_cluster        VARCHAR(64)     COMMENT '子集群',
    backend_info       VARCHAR(256)    COMMENT '后端节点',
    method             VARCHAR(16)     COMMENT 'HTTP 方法',
    res_status_code    SMALLINT        COMMENT '响应状态码',
    err_code           VARCHAR(64)     COMMENT '错误码',
    header_host        VARCHAR(256)    COMMENT '请求 Host',
    ai_provider        VARCHAR(64)     COMMENT '上游模型提供商',
    ai_protocol        VARCHAR(64)     COMMENT 'AI 协议',
    ai_mode            VARCHAR(64)     COMMENT 'AI 模式',
    ai_cost_currency   VARCHAR(16)     COMMENT '成本币种',
    level1Name         VARCHAR(128)    COMMENT 'Level1 标签名',
    level1             VARCHAR(128)    COMMENT 'Level1 标签值',
    level2Name         VARCHAR(128)    COMMENT 'Level2 标签名',
    level2             VARCHAR(128)    COMMENT 'Level2 标签值',
    level3Name         VARCHAR(128)    COMMENT 'Level3 标签名',
    level3             VARCHAR(128)    COMMENT 'Level3 标签值',
    level4Name         VARCHAR(128)    COMMENT 'Level4 标签名',
    level4             VARCHAR(128)    COMMENT 'Level4 标签值',
    level5Name         VARCHAR(128)    COMMENT 'Level5 标签名',
    level5             VARCHAR(128)    COMMENT 'Level5 标签值',
    rate_limit_policy_id VARCHAR(128)  COMMENT '限流策略ID',
    rate_limit_type   VARCHAR(32)     COMMENT '限流类型',
    rate_limit_rule_name VARCHAR(128)  COMMENT '限流规则名',
    ai_auth_reject_reason VARCHAR(256) COMMENT '认证拒绝原因',
    ai_auth_reject_quota_plans_slot1 VARCHAR(128) COMMENT '被拒绝配额计划槽位1',
    ai_auth_reject_quota_plans_slot2 VARCHAR(128) COMMENT '被拒绝配额计划槽位2',
    ai_auth_reject_quota_plans_slot3 VARCHAR(128) COMMENT '被拒绝配额计划槽位3',
    ai_auth_reject_quota_plans_slot4 VARCHAR(128) COMMENT '被拒绝配额计划槽位4',
    ai_auth_reject_quota_plans_slot5 VARCHAR(128) COMMENT '被拒绝配额计划槽位5',

    -- 聚合指标（SUM）
    request_count      BIGINT   SUM    COMMENT '请求数',
    error_count        BIGINT   SUM    COMMENT '错误数',
    auth_reject_count  BIGINT   SUM    COMMENT '认证拒绝数',
    input_tokens       BIGINT   SUM    COMMENT '输入 Token 累计',
    output_tokens      BIGINT   SUM    COMMENT '输出 Token 累计',
    total_tokens       BIGINT   SUM    COMMENT '总 Token 累计',
    ttft_us_sum        BIGINT   SUM    COMMENT 'TTFT 累计（微秒）',
    tpot_us_sum        BIGINT   SUM    COMMENT 'TPOT 累计（微秒）',
    req_header_bytes   BIGINT   SUM    COMMENT '请求头字节累计',
    req_body_bytes     BIGINT   SUM    COMMENT '请求体字节累计',
    res_header_bytes   BIGINT   SUM    COMMENT '响应头字节累计',
    res_body_bytes     BIGINT   SUM    COMMENT '响应体字节累计',
    rate_limit_hits    BIGINT   SUM    COMMENT '限流命中次数',
    backend_retries    BIGINT   SUM    COMMENT '后端重试总次数',
    all_time_sum       BIGINT   SUM    COMMENT '总耗时累计（毫秒）',
    cluster_serve_sum  BIGINT   SUM    COMMENT '集群层耗时累计',
    backend_serve_sum  BIGINT   SUM    COMMENT '后端耗时累计',
    ai_retry_count_sum BIGINT   SUM    COMMENT '模型层重试总次数',
    ai_cost_value_sum  BIGINT   SUM    COMMENT '成本累计（固定点整数）',
    cache_read_tokens  BIGINT   SUM    COMMENT '缓存读取 Token 累计',
    cache_write_tokens BIGINT   SUM    COMMENT '缓存写入 Token 累计',
    ai_audio_input_tokens  BIGINT SUM   COMMENT '音频输入 Token 累计',
    ai_audio_output_tokens BIGINT SUM   COMMENT '音频输出 Token 累计',
    ai_image_count         BIGINT SUM   COMMENT '图片数量累计'
)
AGGREGATE KEY(ts_min, hostid, ai_apikey_id, ai_requested_model, ai_target_model, ai_stream,
              product, cluster, sub_cluster, backend_info, method, res_status_code,
              err_code, header_host, ai_provider, ai_protocol, ai_mode, ai_cost_currency,
              level1Name, level1, level2Name, level2,
              level3Name, level3, level4Name, level4,
              level5Name, level5,
              rate_limit_policy_id, rate_limit_type, rate_limit_rule_name,
              ai_auth_reject_reason,
              ai_auth_reject_quota_plans_slot1, ai_auth_reject_quota_plans_slot2,
              ai_auth_reject_quota_plans_slot3, ai_auth_reject_quota_plans_slot4,
              ai_auth_reject_quota_plans_slot5)
PARTITION BY RANGE(ts_min) (
    PARTITION p_init VALUES LESS THAN ('${INIT_PARTITION_DATE}')
)
DISTRIBUTED BY HASH(ai_apikey_id) BUCKETS 16
PROPERTIES (
    "replication_num" = "1",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-7",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "16",
    "compression" = "zstd"
);