USE ${DORIS_DATABASE};

CREATE JOB bfe_ai_metrics_1m_job
ON SCHEDULE EVERY 1 MINUTE
DO
INSERT INTO bfe_ai_metrics_1m
SELECT
    DATE_TRUNC(log_time, 'minute')       AS ts_min,
    COALESCE(hostid, '')                 AS hostid,
    COALESCE(ai_apikey_id, '')           AS ai_apikey_id,
    COALESCE(ai_requested_model, '')     AS ai_requested_model,
    COALESCE(ai_target_model, '')        AS ai_target_model,
    COALESCE(ai_stream, 0)               AS ai_stream,
    COALESCE(product, '')                AS product,
    COALESCE(cluster, '')                AS cluster,
    COALESCE(sub_cluster, '')            AS sub_cluster,
    COALESCE(backend_info, '')           AS backend_info,
    COALESCE(method, '')                 AS method,
    COALESCE(res_status_code, 0)         AS res_status_code,
    COALESCE(err_code, '')               AS err_code,
    COALESCE(header_host, '')            AS header_host,
    COALESCE(ai_provider, '')            AS ai_provider,
    COALESCE(ai_protocol, '')            AS ai_protocol,
    COALESCE(ai_mode, '')                AS ai_mode,
    COALESCE(ai_cost_currency, '')       AS ai_cost_currency,
    COALESCE(level1Name, '')             AS level1Name,
    COALESCE(level1, '')                 AS level1,
    COALESCE(level2Name, '')             AS level2Name,
    COALESCE(level2, '')                 AS level2,
    COALESCE(level3Name, '')             AS level3Name,
    COALESCE(level3, '')                 AS level3,
    COALESCE(level4Name, '')             AS level4Name,
    COALESCE(level4, '')                 AS level4,
    COALESCE(level5Name, '')             AS level5Name,
    COALESCE(level5, '')                 AS level5,
    COALESCE(ELEMENT_AT(ai_rate_limit_hits, 1).rate_limit_policy_id, '') AS rate_limit_policy_id,
    COALESCE(ELEMENT_AT(ai_rate_limit_hits, 1).rate_limit_type, '')      AS rate_limit_type,
    COALESCE(ELEMENT_AT(ELEMENT_AT(ai_rate_limit_hits, 1).rule_names, 1), '') AS rate_limit_rule_name,
    COALESCE(ai_auth_reject_reason, '')  AS ai_auth_reject_reason,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 1), '') AS ai_auth_reject_quota_plans_slot1,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 2), '') AS ai_auth_reject_quota_plans_slot2,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 3), '') AS ai_auth_reject_quota_plans_slot3,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 4), '') AS ai_auth_reject_quota_plans_slot4,
    COALESCE(ELEMENT_AT(ai_auth_reject_quota_plans, 5), '') AS ai_auth_reject_quota_plans_slot5,
    -- metrics
    COUNT(1)                             AS request_count,
    SUM(CASE WHEN err_code != '' AND err_code IS NOT NULL THEN 1 ELSE 0 END) AS error_count,
    SUM(CASE WHEN ai_auth_reject_reason != '' AND ai_auth_reject_reason IS NOT NULL THEN 1 ELSE 0 END) AS auth_reject_count,
    SUM(COALESCE(ai_input_tokens, 0))    AS input_tokens,
    SUM(COALESCE(ai_output_tokens, 0))   AS output_tokens,
    SUM(COALESCE(ai_total_tokens, 0))    AS total_tokens,
    SUM(COALESCE(ai_ttft_us, 0))         AS ttft_us_sum,
    SUM(COALESCE(ai_tpot_us, 0))         AS tpot_us_sum,
    SUM(COALESCE(req_header_len, 0))     AS req_header_bytes,
    SUM(COALESCE(req_body_len, 0))       AS req_body_bytes,
    SUM(COALESCE(res_header_len, 0))     AS res_header_bytes,
    SUM(COALESCE(res_body_len, 0))       AS res_body_bytes,
    SUM(CASE WHEN ARRAY_SIZE(ai_rate_limit_hits) > 0 THEN 1 ELSE 0 END) AS rate_limit_hits,
    SUM(COALESCE(backend_retry, 0))      AS backend_retries,
    SUM(COALESCE(all_time, 0))           AS all_time_sum,
    SUM(COALESCE(cluster_serve_time, 0)) AS cluster_serve_sum,
    SUM(COALESCE(backend_serve_time, 0)) AS backend_serve_sum,
    SUM(COALESCE(ai_retry_count, 0))     AS ai_retry_count_sum,
    SUM(COALESCE(ai_cost_value, 0))      AS ai_cost_value_sum,
    SUM(COALESCE(ai_cache_read_tokens, 0))  AS cache_read_tokens,
    SUM(COALESCE(ai_cache_write_tokens, 0)) AS cache_write_tokens,
    SUM(COALESCE(ai_audio_input_tokens, 0))  AS ai_audio_input_tokens,
    SUM(COALESCE(ai_audio_output_tokens, 0)) AS ai_audio_output_tokens,
    SUM(COALESCE(ai_image_count, 0))         AS ai_image_count
FROM bfe_ai_request_log
WHERE log_time >= DATE_TRUNC(NOW(), 'minute') - INTERVAL 1 MINUTE
  AND log_time <  DATE_TRUNC(NOW(), 'minute')
GROUP BY ts_min, hostid, ai_apikey_id, ai_requested_model, ai_target_model, ai_stream,
         product, cluster, sub_cluster, backend_info, method, res_status_code,
         err_code, header_host, ai_provider, ai_protocol, ai_mode, ai_cost_currency,
         level1Name, level1, level2Name, level2,
         level3Name, level3, level4Name, level4,
         level5Name, level5,
         rate_limit_policy_id, rate_limit_type, rate_limit_rule_name,
         ai_auth_reject_reason,
         ai_auth_reject_quota_plans_slot1, ai_auth_reject_quota_plans_slot2,
         ai_auth_reject_quota_plans_slot3, ai_auth_reject_quota_plans_slot4,
         ai_auth_reject_quota_plans_slot5;